### ISSUE TITLE
中文名文件上传报错

### ISSUE THREAD

**Issue by bingshushu** [zhangruiyu/tencent_cos#11]
[Flutter Tencent COS] putObject error content: <?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>SignatureDoesNotMatch</Code>
	<Message>The Signature you specified is invalid.</Message>
	<StringToSign>sha1
1680157339;1680157519
fd8170f0893f3185a1471c368104dddea1f83dd9
</StringToSign>
	<FormatString>put
/log/YqNfNc_观众_.log

content-length=778314&amp;content-type=image%2Fjpeg&amp;host=bingbing-1253488539.cos.ap-nanjing.myqcloud.com
</FormatString>
	<Resource>/log/YqNfNc_观众_.log</Resource>
	<RequestId>NjQyNTJhZDdfNDU0ZmI3MDlfMWVjMjhfNDk5OTg1Yg==</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZTg1NTNjZWFlZTA5YzhjYTFlOWFlOTA4OTBiZTI3Yjk=</TraceId>
</Error>

**Comment by zhangruiyu** [comment]
哈喽，我最近暂时没法解决，urlencode一下应该就可以啦，可以自己fork下修改

**Comment by zhangruiyu** [comment]
也可以把url encode后传进去

**Comment by bingshushu** [comment]
不管是cosPath、还是localPath，做了encode后都不行。。。

<img width="922" alt="image" src="https://user-images.githubusercontent.com/7079391/228749925-9af20958-ff7a-4caa-a19f-1d5f1e2cf67a.png">
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/7079391/228749959-521ca766-cdc7-4463-8f19-3265fdf7d41c.png">

**Comment by bingshushu** [comment]
必须去掉objectKey里的所有中文，改为英文，uri. encodeComponent无效。
